export const ADD_DISHES = "ADD_DISHES";
export const REMOVE_DISHES = "REMOVE_DISHES";
export const SET_PURCHASING = 'SET_PURCHASING';

export const INIT_DISHES = 'INIT_DISHES';
export const INIT_ORDER = "INIT_ORDER";

export const FETCH_MENU_FAILURE = "FETCH_MENU_FAILURE";
export const FETCH_MENU_REQUEST = "FETCH_ORDERS_REQUEST";
export const FETCH_MENU_SUCCESS = "FETCH_ORDERS_SUCCESS";

export const ORDER_REQUEST = "ORDER_REQUEST";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAILURE = "ORDER_FAILURE";